import = [
  "~/.config/alacritty/themes/themes/moonfly.toml"
]
[env]
TERM = "xterm-256color"
[window]

padding = {x = 2, y = 2}

decorations = "Buttonless"

opacity = 0.6
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 13

[colors]
#draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#a6a69c"
blue = "#7fb4ca"
cyan = "#7aa89f"
green = "#87a987"
magenta = "#938aa9"
red = "#e46876"
white = "#c5c9c5"
yellow = "#e6c384"

[colors.cursor]
cursor = "#8e8e8e"
text = "#080808"

[colors.normal]
black = "#0d0c0c"
blue = "#8ba4b0"
cyan = "#8ea4a2"
green = "#8a9a7b"
magenta = "#a292a3"
red = "#c4746e"
white = "#c8c093"
yellow = "#c4b28a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[mouse]

hide_when_typing = true
