# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_latte"

# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[♡](bold green) ❯](green)"
error_symbol = "[[♡](bold red) ❯](red)"
vimcmd_symbol = "[♡ ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "bold green"

[directory]
truncation_length = 4
style = "bold blue"

# Palette definitions
[palettes.catppuccin_latte]
red = "#ff5454"
green = "#8cc85f"
yellow = "#e3c78a"
blue = "#80a0ff"
purple = "#cf87e8"
cyan = "#79dac8"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
